### ISSUE TITLE
Ingen möjlighet att bestämma position

### ISSUE THREAD

**Issue by afrxx09** [WheresMarco/1DV450-mh222zr-Client#2]
Hittar inte hur man bestämmer vart ett event ska skapas. Det blir automatiskt där "jag är" och om jag inte tillåter geo location så blir det i havet utanför Ghana. Även om man skriver i siffror i Long och Lat så verkar inte detta tolkas.

**Comment by WheresMarco** [comment]
Det skriver man i lat, long-fälten längst ner på sidan eller fick dom ifyllda genom att klicka på kartan. Men den verkade inte respektera dom på den sidan som låg live. Fixat nu.
