### ISSUE TITLE
Skapa plats utan data

### ISSUE THREAD

**Issue by afrxx09** [WheresMarco/1DV450-mh222zr-Client#4]
Applikationen tillåter att skapa event utan att ange någon information i formuläret. Kan inte se om det faktiskt skapas några event då alla blir på samma position(dvs min nuvarande som jag inte lyckas ändra) men det dyker upp ett meddelande att eventet har skapats.

**Comment by WheresMarco** [comment]
Har slängt in lite validering för att förhindra det.
