### ISSUE TITLE
Sammanfattning

### ISSUE THREAD

**Issue by afrxx09** [WheresMarco/1DV450-mh222zr-Client#6]
###Kod och filstruktur

Mycket väl strukturerad kod. Det är enkelt att hitta i den, namngivning av både filer, klasser och variabler känns genomtänkt. Inga konstigheter alls.

###Gränssnitt

Bra, snyggt gränssnitt men hade kunnat finslipas lite på kartan. Transparens är snyggt men det blir lite svårt att se vad det står i formulärfälten.

###Funktionalitet

Det finns lite buggar som nämnts i andra issues. Men över lag tycker jag applikationen gör det den ska.

Bra jobbat

**Comment by WheresMarco** [comment]
Tack för feedbacken :smile:
